baseurl: 
pygments: true
markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
  highlighter: rouge
  coderay:
    coderay_line_numbers:  nil
